eureka:
  client:
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: gateway
  cloud:
    discovery:
      gateway:
        locator:
          enabled: true
server:
  port: 8060